### ISSUE TITLE
Problém s použitím.

### ISSUE THREAD

**Issue by Samuel-2000** [suzrz/nnvis#5]
Dobrý deň. dalo by sa vám zdielať nejaké skripty aby som vedel ako používať váš program nnvis? nakoľko nadväzujem na vašu bakalársku prácu, a potrebujem k tomu pracovať s vašim programom. Váš program bude pravdepodobne knižnica, nakoľko neobsahuje súbor main. Ale chýba tu dokumentácia, ktorá by vysvetlovala jej použitie.
Ak vám ostali nejaké skripty, tak by som bol rád, ak by ste ich pushnula sem na git, poprípade mi ich poslala na email: xkucht11@stud.fit.vutbr.cz alebo samuellkuchta@gmail.com
Vopred ďakujem za váš čas.
S pozdravom,
Samuel Kuchta.

**Comment by su-perplex** [comment]
Ahoj, klidne mi muzes tykat :) Vic info o projektu je v hlavnim repozitari: https://github.com/suzrz/vis_net_loss_landscape Tento je jen pro balik na pypi. Klidne se ozvi na mail: nemcova.silva@gmail.com pokud budes potrebovat dalsi pomoc. Pokud bude vse ok, prosim pak zavri tuto issue.
